// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMfhs11GrOzIxUaQfKLfJgSFXuckuLrQ',
    appId: '1:50753149040:android:6db75f1041a7119fa97cb5',
    messagingSenderId: '50753149040',
    projectId: 'quero-obras-notification',
    databaseURL: 'https://quero-obras-notification-default-rtdb.firebaseio.com',
    storageBucket: 'quero-obras-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOwKkHT4shMclX29JKqCOwuQobSwOXY0',
    appId: '1:50753149040:ios:6fb2a62248088d8ca97cb5',
    messagingSenderId: '50753149040',
    projectId: 'quero-obras-notification',
    databaseURL: 'https://quero-obras-notification-default-rtdb.firebaseio.com',
    storageBucket: 'quero-obras-notification.firebasestorage.app',
    iosBundleId: 'com.popopipo.queroobras',
  );

}